### ISSUE TITLE
Improve Performance of RSS Ingestion Pipeline

### ISSUE THREAD

**Issue by lukasgraef** [oth-datapipeline/ingestion-scripts#14]
Currently, faust-streaming can't keep up with the messages coming from kafka, resulting in lost message
-> Batch Processing in faust could mitigate or solve those performance issues

**Comment by lukasgraef** [comment]
Error Message in Faust:

![grafik](https://user-images.githubusercontent.com/48957581/162800159-191814b2-77fe-4520-91fe-5d23ec041469.png)

**Comment by dnzxy** [comment]
@lukasgraef maybe add a `_createdAt` field for each event when inserting into mongo, so that we can verify when events where pushed into mongo.
